### ISSUE TITLE
Skip problematic forms when iterating over invitations to send

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-invite#59]
Right now, we have the possibility of a KeyError being raised [here](https://github.com/unt-libraries/django-invite/blob/e171e55ff356f197a605d215d3715eb308bac28a/invite/views.py#L276). We don't see it happen in normal use, but it could plausibly happen in a situation where you are resubmitting a form from like a refresh or using the back button. It should be simple enough to skip the current form if there is an issue like the first_name not being populated. Additionally, it should be explored whether or not it would be feasible to alert the user if a form that isn't completely blank has been skipped for whatever reason.

**Comment by ldko** [comment]
@gracieflores can you verify this issue still exists and if so, fix it? Thank you in advance!

**Comment by gracieflores** [comment]
So this one is a little strange, but I do think I found the best solution. I wanted to get your input before I created the PR. So the issue does still exists, but I don't really see this happening a lot. The problem is only there if someone hits the back button and refreshes the page after submitting 2 or more invitations. The issue happens in chrome and firefox. If you only hit the back button you can't really do much because there is some javascript that prevents you from re-submitting.

So, if you do happen to go back and hit refresh then you run into problems. On refresh, if you had multiple input forms, the forms reduce to only one (visually). If you inspect the forms, you will see a hidden input for forms-TOTAL_FORMS. This is where we have a problem on refresh, it doesn't update the total number of forms.

My solution is to reset the forms and the total form count when someone hits refresh on the invite page that has already been submitted. This allows them to input new information for submission.

My original solution was to add a try/except to allow for re-submission on the valid form and skip the forms it thinks exists because of the incorrect count.
